name: PowerShell Script Test

on:
  push:
    branches: [ GUID ]
  pull_request:
    branches: [ GUID ]

jobs:
  test:
    name: Run PowerShell Tests
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PowerShell environment
      shell: pwsh
      run: |
        # Setup test directories as environment variables
        echo "TEST_SOURCE_DIR=${Env:GITHUB_WORKSPACE}\testSource" >> $GITHUB_ENV
        echo "TEST_TARGET_DIR=${Env:GITHUB_WORKSPACE}\testTarget" >> $GITHUB_ENV
        echo "TEST_BACKUP_DIR=${Env:GITHUB_WORKSPACE}\testBackup" >> $GITHUB_ENV

        # Create the directories
        New-Item -ItemType Directory -Path ${{ env.TEST_SOURCE_DIR }}, ${{ env.TEST_TARGET_DIR }}, ${{ env.TEST_BACKUP_DIR }} -Force

        # Create a test file
        $testFile = Join-Path ${{ env.TEST_SOURCE_DIR }} "testFile.txt"
        "Test content" | Out-File -FilePath $testFile

    - name: Install Pester
      shell: pwsh
      run: |
        Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Run PowerShell Script Tests
      shell: pwsh
      run: |
        Invoke-Pester .\test\ps_pipeline.Tests.ps1 -Output Detailed
