name: PowerShell Script Test

on:
  push:
    branches: [ GUID ]
  pull_request:
    branches: [ GUID ]

jobs:
  test:
    name: Run PowerShell Tests
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PowerShell environment
      shell: pwsh
      run: |
        # Setup test directories as environment variables
        echo "TEST_SOURCE_DIR=${Env:GITHUB_WORKSPACE}\testSource" | Out-File -FilePath $Env:GITHUB_ENV -Append
        echo "TEST_TARGET_DIR=${Env:GITHUB_WORKSPACE}\testTarget" | Out-File -FilePath $Env:GITHUB_ENV -Append
        echo "TEST_BACKUP_DIR=${Env:GITHUB_WORKSPACE}\testBackup" | Out-File -FilePath $Env:GITHUB_ENV -Append

    - name: Create test directories and file
      shell: pwsh
      run: |
        # Create the directories
        New-Item -ItemType Directory -Path $Env:TEST_SOURCE_DIR, $Env:TEST_TARGET_DIR, $Env:TEST_BACKUP_DIR -Force
        
        # Create a test file
        $testFile = Join-Path $Env:TEST_SOURCE_DIR "testFile.txt"
        "Test content" | Out-File -FilePath $testFile

    - name: Install Pester
      shell: pwsh
      run: |
        Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Run PowerShell Script Tests
      shell: pwsh
      run: |
        Invoke-Pester .\test\ps_pipeline.Tests.ps1 -Output Detailed
