name: PowerShell Script Test

on:
  push:
    branches: [ GUID ]
  pull_request:
    branches: [ GUID ]

jobs:
  test:
    name: Run PowerShell Tests
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PowerShell environment
      shell: pwsh
      run: |
        # Setup test directories
        $testSourceDir = "${Env:GITHUB_WORKSPACE}\testSource"
        $testTargetDir = "${Env:GITHUB_WORKSPACE}\testTarget"
        $testBackupDir = "${Env:GITHUB_WORKSPACE}\testBackup"
        New-Item -ItemType Directory -Path $testSourceDir, $testTargetDir, $testBackupDir -Force

        # Create a test file
        $testFile = "${testSourceDir}\testFile.txt"
        "Test content" | Out-File -FilePath $testFile

    - name: Install Pester
      shell: pwsh
      run: |
        Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Run PowerShell Script Tests
      shell: pwsh
      run: |
        Invoke-Pester .\test\ps_pipeline.Tests.ps1 -Output Detailed
